name: Punch in

on:
  schedule:
    - cron: '* 2 * * *'
    - cron: '* 11 * * *'

jobs:
  attendence:
    name: do_punch
    runs-on: ubuntu-latest
    env:
      ACCOUNT: ${{ secrets.ACCOUNT}}
      PASSWORD: ${{ secrets.PASSWORD}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: debug
      #   uses: ./
      #   with:
      #     mode: out
      - name: Punch in
        if: github.event.schedule != '* 2 * * *'
        uses: ./
        with:
          mode: in
      - name: Punch out
        if: github.event.schedule != '* 11 * * *'
        uses: ./
        with:
          mode: out
