name: Punch in

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '* 10 * * *'
    - cron: '* 19 * * *'


permissions:
  contents: read
  issues: write

jobs:
  attendence:
    name: do_punch
    runs-on: ubuntu-latest
    env:
      ACCOUNT: ${{ secrets.ACCOUNT}}
      PASSWORD: ${{ secrets.PASSWORD}}
    steps:
      - name: debug
        uses: ./
        with:
          mode: in
      # - name: Punch in
      #   if: github.event.schedule != '* 10 * * *'
      #   uses: ./
      #   with:
      #     mode: in
      # - name: Punch out
      #   if: github.event.schedule != '* 19 * * *'
      #   uses: ./
      #   with:
      #     mode: out
